[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
    bodmer/TFT_eSPI @ ^2.5.43
build_flags =
    -DWIFI_SSID='"${WIFI_SSID}"'
    -DWIFI_PASS='"${WIFI_PASS}"'
    -DMQTT_BROKER='"${MQTT_BROKER}"'
    -DMQTT_USER='"${MQTT_USER}"'
    -DMQTT_PASS='"${MQTT_PASS}"'
